apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
data:
  root-db-pass: {{ .Values.mariadb.rootPassword | b64enc }}  # rootpass
  db-pass: {{ .Values.mariadb.password | b64enc }} # cvpass